spring.application.name=proyecto-acueducto
spring.datasource.url=jdbc:mysql://localhost:3306/proyecto_acueducto
spring.datasource.username=root
spring.datasource.password=Juliana_2026

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true